### ISSUE TITLE
Make access pattern of tile fetching more realistic

### ISSUE THREAD

**Issue by zachmullen** [DigitalSlideArchive/histomics_load_testing#1]
This may help avoid unintended cache-related artifacts in our experiments.

**Comment by manthey** [comment]
Is it a concern that accesses are almost never actually random, so this may make the behavior less like real-world use?

**Comment by zachmullen** [comment]
Definitely. I think a good simulated access pattern would be:

1. Each client starts out on the highest resolution
2. Each client picks a specific region at random to zoom in on, and does so
3. We add jitter to the start of each client as well as the zoom

**Comment by zachmullen** [comment]
We should also consider firing multiple requests off in parallel and awaiting them rather than firing them one by one and awaiting the response, as I believe in real usage the browser will be sending multiple in parallel.

**Comment by zachmullen** [comment]
We should also consider firing multiple requests off in parallel and awaiting them rather than firing them one by one and awaiting the response, as I believe in real usage the browser will be sending multiple in parallel.

**Comment by manthey** [comment]
Our typically client has five requests simultaneously pending.

**Comment by zachmullen** [comment]
Good to know. If we want to go that parallel-awaiting route, we could follow the green thread pattern cited here: https://github.com/locustio/locust/issues/1251

**Comment by zachmullen** [comment]
Closing this until we have more actionable items. #3 may be all we need.
